[arm]
arm-dem-kaleikino ansible_host=172.17.192.3 ansible_user=administrator ansible_password=Bzpa%123456789
#test-arm ansible_host=192.168.77.150 ansible_user=administrator ansible_password=Bzpa%123456789
#test-arm ansible_host=192.168.77.136 ansible_user=administrator ansible_password=Bzpa%123456789
#arm-mns-osn-sokur ansible_host=192.168.201.145 ansible_user=administrator ansible_password=Bzpa%123456789
#arm-mns-res-sokur ansible_host=192.168.201.132 ansible_user=administrator ansible_password=Bzpa%123456789
#arm-pt-osn-sokur ansible_host=192.168.193.145 ansible_user=administrator ansible_password=Bzpa%123456789
#arm-pt-res-sokur ansible_host=192.168.193.132 ansible_user=administrator ansible_password=Bzpa%123456789

[arm:vars]
ansible_python_interpreter=/usr/bin/python3
#ansible_python_interpreter=/usr/bin/python3
#ansible_connection=ssh
#ansible_user=administrator
#ansible_ssh_pass=Bzpa/123456789
