#!/bin/bash

echo '[ShortCutKeys]' > /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None0="ksysguard --autosu"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None1="ksysguard --autosu"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None2="assistant -collectionFile /usr/share/doc/fly/qthelp/ru/flyhelp.qhc"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None3="fly-run"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None4="spectacle -a"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None5="x-terminal-emulator"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None6="fly-wmfunc FLYWM_GOTO_PAGING 1"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None7="fly-wmfunc FLYWM_GOTO_PAGING 2"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None8="fly-wmfunc FLYWM_GOTO_PAGING 3"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None9="fly-wmfunc FLYWM_GOTO_PAGING 4"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None10="/usr/bin/fly-touchpad-toggle.sh"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None11="assistant -collectionFile /usr/share/doc/fly/qthelp/ru/flyhelp.qhc"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None12="firefox"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None13="kcalc || speedcrunch"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None14="fly-notifications --interactiveSwitchDoNotDisturbMode"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None15="fly-fm"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None16="fly-find -d -s ~"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None17="gwenview"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None18="chromium"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None19="fly-admin-center"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None20="kate"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None21="fly-notifications --switchVisible"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None22="dbus-send  --session  --dest=org.kde.kglobalaccel  --type=method_call  /component/kscreend  org.kde.kglobalaccel.Component.invokeShortcut string:display"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None23="kinfocenter"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None24="fly-run"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None25="pavucontrol || pavucontrol-qt"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None26="goldendict"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None27="spectacle -r -b -c"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None28="goldendict `xsel -p -o`"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None29="x-terminal-emulator"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None30="libreoffice --writer"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None31="spectacle -f"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None32="fly-sound-applet --down"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None33="vlc"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None34="fly-sound-applet --micMute"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None35="fly-sound-applet --mute"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None36="fly-sound-applet --up"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None37="fly-record"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None38="qbat"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None39="kcalc || speedcrunch"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None40="fly-admin-date"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None41="vlc"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None42="libreoffice --writer"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None43="eject"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None44="libreoffice --calc"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None45="fly-fm"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None46="fly-fm ~"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None47="thunderbird"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None48="vlc"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None49="gwenview"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None50="fly-find -d"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None51="x-terminal-emulator"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None52="/usr/bin/fly-touchpad-toggle.sh"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None53="vlc"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None54="fly-videocamera"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None55="libreoffice --writer"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None56="firefox"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|None57="ksysguard --autosu"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|a="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|f="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|KP_Enter="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Return="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Delete="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|KP_Delete="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|KP_Enter="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|Return="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Delete="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|KP_Delete="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|x="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|c="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Insert="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|v="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Insert="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|KP_Up="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Up="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Down="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|KP_Down="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|KP_Left="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Left="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|KP_Right="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Right="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|F2="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|z="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Mod4|Left="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Mod4|Right="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Mod4|Up="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Mod4|Down="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Super_L="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Super_R="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Super_L="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Super_R="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Super_L="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Super_R="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|F3="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|space="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|d="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|m="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|KP_Right="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|Right="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|KP_Left="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|Left="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|Down="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|Up="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|F11="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|F11="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|Right="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|Left="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Alt|Up="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Alt|Down="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|F4="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|Tab="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Alt|Tab="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|Escape="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Alt|Escape="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|Delete="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Alt|Delete="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|Insert="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|l="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|less="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|greater="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Alt|Delete="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Alt|KP_Delete="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|F1="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|F2="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|Print="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|t="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|Ctrl|Delete="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|F1="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|F2="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|F3="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|F4="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Mod4|XF86TouchpadToggle="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|a="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|b="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|c="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Mod4|d="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|e="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|f="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|g="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|h="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|i="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|k="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|n="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|p="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|Pause="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|r="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|s="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|c="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|s="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Shift|Mod4|x="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|t="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Mod4|w="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Print="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86AudioLowerVolume="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86AudioMedia="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86AudioMicMute="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86AudioMute="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86AudioRaiseVolume="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86AudioRecord="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Battery="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Calculater="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Calendar="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86CD="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Documents="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Eject="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Excel="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Explorer="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86HomePage="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Mail="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Music="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Pictures="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Search="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Terminal="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86TouchpadToggle="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Video="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86WebCam="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86Word="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|XF86WWW="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Ctrl|Shift|Escape="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'Alt|Print="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
echo 'None|Print="Disable"' >> /usr/share/fly-wm/keyshortcutrc.fly-kiosk
