---
- name: kics update
  hosts: arm
  become: yes
  become_user: root
  vars:
    project_dir: /usr/local/Project
  tasks:

### kics_update  ###

    - name: Удаляю старые обновления
      ansible.builtin.file:
        path: '/opt/kics_update'
        state: absent

    - name: Распаковываю архив с новыми обновлениями
      ansible.builtin.unarchive:
        src: '{{ project_dir }}/files/kics_update.tar'
        dest: '/opt'
        owner: root
        group: root
        mode: 'u=rwX,g=rX,o=rX'

    - name: Запускаю задачу обновления баз
      ansible.builtin.command:
        cmd: 'kics-control --start-task 6 --progress'

    - name: Перезапускаю kics.service
      ansible.builtin.systemd:
        name: kics.service
        state: restarted

    - name: Запускаю задачу сканирования компьютера
      ansible.builtin.command:
        cmd: 'kics-control --start-task 2'

    - name: Блокирую интерпритаторы
      ansible.builtin.script:
        cmd: /usr/local/Project/scripts/shell/enable_chmodx.sh
...
