---
- name: Installation MegaCli
  hosts: arm
  become: yes
  become_user: root
  vars:
    iso_name: installation-1.8.5.46-11.02.26_01.30-di.iso
    project_dir: /usr/local/Project
    install_dir: /usr/local/Project/install
    repository_dir: /usr/local/alse
    venv_path: /usr/local/Project/venv
  tasks:

### install MegaCli ###

    - name: Создание временной директории megacli
      ansible.builtin.file:
        path: '{{ install_dir }}/megacli'
        state: directory
        owner: root
        group: root
        mode: 'u=rwX,g=rX,o=rX'

    - name: Распаковка архива MegaCLI.zip
      ansible.builtin.unarchive:
        src: '{{ project_dir }}/install/8-07-14_MegaCLI.zip'
        dest: '{{ install_dir }}/megacli'
        owner: root
        group: root
        mode: 'u=rwX,g=rX,o=rX'

    - name: Распаковка архива alien.tar
      ansible.builtin.unarchive:
        src: '{{ install_dir }}/alien.tar'
        dest: '{{ install_dir }}'
        owner: root
        group: root
        mode: 'u=rwX,g=rX,o=rX'

    - name: Распаковка архива libncurses5.tar
      ansible.builtin.unarchive:
        src: '{{ install_dir }}/libncurses5.tar'
        dest: '{{ install_dir }}'
        owner: root
        group: root
        mode: 'u=rwX,g=rX,o=rX'

    - name: Установка alien из deb-пакета
      ansible.builtin.shell:
        cmd: 'dpkg -i {{ install_dir }}/alien/*.deb'

    - name: Установка libncurses5 из deb-пакета
      ansible.builtin.shell:
        cmd: 'dpkg -i {{ install_dir }}/libncurses5/*.deb'

    - name: Конвертация MegaCli-8.07.14-1.noarch.rpm в deb-формат
      ansible.builtin.command:
        cmd: 'alien MegaCli-8.07.14-1.noarch.rpm'
        chdir: '/usr/local/Project/install/megacli/Linux'

    - name: Установка MegaCli из deb-пакета
      ansible.builtin.shell:
        cmd: 'dpkg -i {{ install_dir }}/megacli/Linux/*.deb'

    - name: Создание ссылки megacli -> /opt/MegaRAID/MegaCli/MegaCli64
      ansible.builtin.file:
        src: '/opt/MegaRAID/MegaCli/MegaCli64'
        dest: '/usr/bin/megacli'
        state: link

    - name: Удаление временных директорий
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ install_dir }}/alien'
        - '{{ install_dir }}/libncurses5'
        - '{{ install_dir }}/megacli'

    - name: Создание файла raid_state
      ansible.builtin.file:
        path: '{{ project_dir }}/raid_state'
        state: touch
        owner: root
        group: root
        mode: 'u=rw,g=r,o=r'

    - name: Копирование скрипта RAID.sh
      ansible.builtin.copy:
        src: '{{ project_dir }}/scripts/shell/RAID.sh'
        dest: /usr/local/Project/
        owner: root
        group: root
        mode: 'u=rwx,g=rx,o=rx'

    - name: Выполнение скрипта raid_state.py
      ansible.builtin.script:
        cmd: '{{ project_dir }}/scripts/python/raid_state.py'
        executable: '{{ venv_path }}/bin/python3'

    - name: astra-nochmodx-lock enable
      ansible.builtin.script:
        cmd: '{{ project_dir }}/scripts/shell/enable_chmodx.sh'

...
