---
- name: Installation MegaCli
  hosts: arm
  become: yes
  become_user: root
  vars:
    iso_name: installation-1.8.5.46-11.02.26_01.30-di.iso
    project_dir: /usr/local/Project
    install_dir: /usr/local/Project/install
    repository_dir: /usr/local/alse
  tasks:

### install MegaCli ###

    - name: unzip MegaCLI.zip
      ansible.builtin.unarchive:
        src: '{{ project_dir }}/install/8-07-14_MegaCLI.zip'
        dest: '{{ install_dir }}/megacli'
        owner: root
        group: root
        mode: u=rwX,g=rX,o=rX

    - name: untar alien.tar
      ansible.builtin.unarchive:
        src: '{{ install_dir }}/alien.tar'
        dest: '{{ install_dir }}'
        owner: root
        group: root
        mode: u=rwX,g=rX,o=rX

    - name: untar libncurses5.tar
      ansible.builtin.unarchive:
        src: '{{ install_dir }}/libncurses5.tar'
        dest: '{{ install_dir }}'
        owner: root
        group: root
        mode: u=rwX,g=rX,o=rX

    - name: install alien
      ansible.builtin.command:
        cmd: 'dpkg -i {{ install_dir }}/alien/*.deb'

    - name: install libncurses5
      ansible.builtin.command:
        cmd: 'dpkg -i {{ install_dir }}/libncurses5/*.deb'

    - name: convert MegaCli-8.07.14-1.noarch.rpm
      ansible.builtin.command: 
        cmd: 'alien MegaCli-8.07.14-1.noarch.rpm'
        chdir: '/usr/local/Project/install/megacli/Linux'

    - name: install MegaCli
      ansible.builtin.command:
        cmd: 'dpkg -i {{ install_dir }}/megacli/Linux/*.deb'

    - name: create link for megacli
      ansible.builtin.command:
        cmd: 'ln -s /opt/MegaRAID/MegaCli/MegaCli64 /usr/bin/megacli'

    - name: delete directory megacli
      ansible.builtin.file:
        path: '{{ install_dir }}/megacli'
        state: absent

    - name: delete directory alien
      ansible.builtin.file:
        path: '{{ install_dir }}/alien'
        state: absent

    - name: delete directory libncurses5
      ansible.builtin.file:
        path: '{{ install_dir }}/libncurses5'
        state: absent

    - name: create /usr/local/Project/raid_state
      ansible.builtin.file:
        path: '{{ project_dir }}/raid_state'
        state: touch
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: copy RAID.sh
      ansible.builtin.copy:
        src: '{{ project_dir }}/scripts/shell/RAID.sh'
        dest: /usr/local/Project/
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: run script raid_state.sh
      ansible.builtin.script:
        cmd: '{{ project_dir }}/scripts/python/raid_state.py'

    - name: astra-nochmodx-lock enable
      ansible.builtin.script:
        cmd: '{{ project_dir }}/scripts/shell/enable_chmodx.sh'

...
