---
- name: ARM Settings
  hosts: arm
  become: yes
  become_user: root
  vars:
    iso_name: installation-1.8.5.46-11.02.26_01.30-di.iso
    project_dir: /usr/local/Project
    install_dir: /usr/local/Project/install
    repository_dir: /usr/local/alse
    venv_path: /usr/local/Project/venv
  tasks:

    - name: Распаковка архива systemdunitparser-0.4.tar.gz
      ansible.builtin.unarchive:
        src: '{{ install_dir }}/systemdunitparser-0.4.tar.gz'
        dest: '{{ install_dir }}'
        mode: '0755'

    - name: Установка библиотеки SystemdUnitParser в venv
      ansible.builtin.pip:
        name: '{{ install_dir }}/systemdunitparser-0.4'
        virtualenv: "{{ venv_path }}"
        virtualenv_command: python3 -m venv
        state: present

    - name: Выполнение скрипта alpha_start_hmi.py
      ansible.builtin.script:
        cmd: '{{ project_dir }}/scripts/python/alpha_start_hmi.py'
        executable: '{{ venv_path }}/bin/python3'

    - name: Выполнение скрипта fscontrol-service.py
      ansible.builtin.script:
        cmd: '{{ project_dir }}/scripts/python/fscontrol-service.py'
        executable: '{{ venv_path }}/bin/python3'

...
