---
- name: Create Users
  hosts: arm
  become: yes
  become_user: root
  vars:
    iso_name: installation-1.8.5.46-11.02.26_01.30-di.iso
    project_dir: /usr/local/Project
    install_dir: /usr/local/Project/install
    repository_dir: /usr/local/alse
  tasks:

### create directores for new project ###

    - name: create directory /usr/local/Project
      shell: "sudo mkdir -p {{ project_dir }}"

    - name: rights to the Project folder
      shell: "sudo chmod 0777 -R {{ project_dir }}"

    - name: create directory for install
      shell: "sudo mkdir -p {{ install_dir }}"

    - name: rights to the install folder
      shell: "sudo chmod 0777 -R {{ install_dir }}"


### install ConfigUpdater-3.2.tar.gz for python3 ###

    - name: copy ConfigUpdater-3.2.tar.gz
      copy:
        src: '{{ install_dir }}/ConfigUpdater-3.2.tar.gz'
        dest: /usr/local/Project/install/ConfigUpdater-3.2.tar.gz
        owner: root
        group: root
        mode: '0644'

    - name: untar ConfigUpdater-3.2.tar.gz
      shell: 'sudo tar -C {{ install_dir }} -xvf {{ install_dir }}/ConfigUpdater-3.2.tar.gz'

    - name: rm /usr/local/Project/install/ConfigUpdater-3.2.tar.gz
      shell: 'sudo rm {{ install_dir }}/ConfigUpdater-3.2.tar.gz'

    - name: install ConfigUpdater-3.2
      command: python3 setup.py install
      args:
        chdir: /usr/local/Project/install/ConfigUpdater-3.2

    - name: delete /usr/local/Project/install/ConfigUpdater-3.2
      shell: 'sudo rm -rf {{ install_dir }}/ConfigUpdater-3.2'


### create local repository ###

    - name: copy iso
      copy:
        src: '{{ install_dir }}/{{ iso_name }}'
        dest: '{{ install_dir }}/{{ iso_name }}'

    - name: mount iso
      shell: 'sudo mkdir -p /mnt/iso && sudo mount {{ install_dir }}/{{ iso_name }} /mnt/iso'

    - name: create repository
      shell: "sudo mkdir -p {{ repository_dir }} && sudo cp -r /mnt/iso {{ repository_dir }}"

    - name: umount iso
      shell: "sudo umount /mnt/iso"

    - name: add repository
      script: /usr/local/Project/scripts/python/repository.py

### default users settings ###

    - name: /usr/share/fly-wm/theme/default.themerc and /usr/share/fly-wm/theme/default.themerc.fly-kiosk
      script: /usr/local/Project/scripts/python/defaul_user_settings.py

    - name: usr/share/fly-wm/keyshortcutrc.fly-kiosk
      script: /usr/local/Project/scripts/shell/keyshortcutrc.sh

    - name: backup /usr/share/fly-wm/ru_RU.UTF-8.miscrc.fly-kiosk
      shell: 'sudo cp /usr/share/fly-wm/ru_RU.UTF-8.miscrc.fly-kiosk /usr/share/fly-wm/ru_RU.UTF-8.miscrc.fly-kiosk.bak'

    - name: copy /usr/share/fly-wm/ru_RU.UTF-8.miscrc.fly-kiosk
      copy:
        src: /usr/local/Project/files/ru_RU.UTF-8.miscrc.fly-kiosk
        dest: /usr/share/fly-wm/ru_RU.UTF-8.miscrc.fly-kiosk
        owner: root
        group: root
        mode: '0644'

### create new users ###

    - name: execute script create_users.py
      script: /usr/local/Project/scripts/python/create_users.py

    - name: copy /home/operator_arm/.fly
      copy:
        src: /usr/local/Project/files/operator_arm/.fly/
        dest: /home/operator_arm/.fly/
        owner: operator_arm
        group: operator_arm
        directory_mode:

    - name: copy fly-kiosk for operator_arm
      copy:
        src: /usr/local/Project/files/fly-kiosk/operator_arm/
        dest: /etc/fly-kiosk/operator_arm/
        owner: root
        group: operator_arm
        directory_mode:

    - name: chown /etc/fly-kiosk/operator_arm/fly-kiosk.conf
      shell: "sudo chown root:root /etc/fly-kiosk/operator_arm/fly-kiosk.conf"

    - name: execute script create_start_hmi.py
      script: /usr/local/Project/scripts/python/create_start_hmi.py

### audit settings ###

    - name: backup old logrotate.conf
      shell: 'sudo mv /etc/logrotate.conf /etc/logrotate.conf.bak'

    - name: copy logrotate.conf
      copy:
        src: /usr/local/Project/files/logrotate.conf
        dest: /etc/logrotate.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy audit01.rules
      copy:
        src: /usr/local/Project/files/audit01.rules
        dest: /etc/audit/rules.d/audit01.rules
        owner: root
        group: root
        mode: '0644'

    - name: copy /etc/audit/files/auditd.conf
      copy:
        src: /usr/local/Project/files/auditd.conf
        dest: /etc/audit/auditd.conf
        owner: root
        group: root
        mode: '0644'

    - name: copy /etc/audit/5-exclude.rules
      copy:
        src: /usr/local/Project/files/5-exclude.rules
        dest: /etc/audit/rules.d/5-exclude.rules
        owner: root
        group: root
        mode: '0644'

    - name: create user's audit
      shell: "sudo useraud -o 0:0"

    - name: create admin's audit
      shell: "sudo useraud administrator 0:0"

    - name: restart auditd.service
      systemd:
        name: auditd
        enabled: yes
        state: restarted

    - name: logrotate settings
      script: /usr/local/Project/scripts/python/logrotate.py

    - name: create file finalize audit
      script: /etc/audit/rules.d/99-finalize.rules

### snmp ###

    - name: install snmpd
      apt:
        name: snmpd
        state: present

    - name: execute script snmpd.py
      script: /usr/local/Project/scripts/python/snmpd.py

### chrony ###

    - name: install chrony
      apt:
        name: chrony
        state: present

    - name: execute script chrony.py
      script: /usr/local/Project/scripts/python/chrony.py

### grub settings ###

    - name: grub settings
      script: /usr/local/Project/scripts/python/grub.py

### ssh settings ###

    - name: ssh Settings
      script: /usr/local/Project/scripts/python/ssh.py

### fscontrol ###

    - name: copy fscontrol files
      copy:
        src: '{{ install_dir }}/FSControl'
        dest: /usr/local/Project/install/
        owner: root
        group: root
        mode: '0755'

    - name: install libicu70_70.1-2_amd64.deb
      shell: 'sudo dpkg -i {{ install_dir }}/FSControl/libicu70_70.1-2_amd64.deb'

    - name: install libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
      shell: 'sudo dpkg -i {{ install_dir }}/FSControl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb'

    - name: install FSControl.1.0.37.linux-x64.deb
      shell: 'sudo dpkg -i {{ install_dir }}/FSControl/FSControl.1.0.37.linux-x64.deb'

    - name: untar aspnetcore-runtime-8.0.13-linux-x64.tar.gz
      shell: 'sudo tar -C /opt/FSControl -xvf {{ install_dir }}/FSControl/aspnetcore-runtime-8.0.13-linux-x64.tar.gz'

    - name: chmod for /etc/systemd/system/FSControl.service
      shell: 'sudo chmod 644 /etc/systemd/system/FSControl.service'

    - name: run script fscontrol-service.py
      script: /usr/local/Project/scripts/python/fscontrol-service.py

    - name: create directory /opt/FSControlUI
      shell: 'sudo mkdir -p /opt/FSControlUI'

    - name: FSControl.ElectronApp-2.0.0.AppImage in /opt/FSControlUI
      shell: 'sudo cp {{ install_dir }}/FSControl/FSControl.ElectronApp-2.0.0.AppImage /opt/FSControlUI/'

    - name: chmod FSControl.ElectronApp-2.0.0.AppImage
      shell: 'sudo chmod +x /opt/FSControlUI/FSControl.ElectronApp-2.0.0.AppImage'

    - name: create group fscontrol
      shell: 'sudo groupadd fscontrol'

    - name: administrator in fscontrol group
      shell: 'sudo usermod -aG fscontrol administrator'

    - name: chmod /opt/FSControl/appsettings_unix.json
      shell: 'sudo chmod 644 /opt/FSControl/appsettings_unix.json'

    - name: run script fscontrol-json.py
      script: /usr/local/Project/scripts/python/fscontrol-json.py

    - name: enable FSControl.service
      shell: 'sudo systemctl enable FSControl.service'

    - name: start FSControl.service
      shell: 'sudo systemctl start FSControl.service'

### clear bash history ###

    - name: run script rm_bash_history.sh
      script: /usr/local/Project/scripts/shell/rm_bash_history.sh

### visudo ###

    - name: run script visudo.py
      script: /usr/local/Project/scripts/python/visudo.py

### usbguard ###

    - name: install usbguard
      apt:
        name: usbguard
        state: present

    - name: enable usbguard
      shell: "sudo systemctl enable usbguard"

    - name: start usbguard
      shell: "sudo systemctl start usbguard"

    - name: run script usdguard.py
      script: /usr/local/Project/scripts/python/usdguard.py

    - name: run script usdguard_rule.py
      script: /usr/local/Project/scripts/python/usdguard_rule.py

### disable autoupdate ###

    - name: run script disable_autoupdate.py
      script: /usr/local/Project/scripts/python/disable_autoupdate.py

### delete autostart ###

    - name: run script autostart_arm.sh
      script: /usr/local/Project/scripts/shell/autostart_arm.sh

...
