# End User License Agreement flag must be 'yes' (required)"
# See /opt/kaspersky/kics/doc/license.<lang> for details
EULA_AGREED=yes

# Privacy Policy agreement flag must be 'yes' (required)"
# See /opt/kaspersky/kics/doc/license.<lang> for details
PRIVACY_POLICY_AGREED=yes

# Use KSN: yes|no (required)
# See /opt/kaspersky/kics/doc/ksn_license.<lang> for details
USE_KSN=no

# Set up the service default locale
LOCALE=ru_RU.UTF-8

# Activation code or key file
#INSTALL_LICENSE=""

# Set up updater source: KLServers|SCServer|<url>
UPDATER_SOURCE=/opt/kics_update

# Set up proxy server: none|<url>
PROXY_SERVER=none

# Run the anti-virus database update procedure: yes|no
UPDATE_EXECUTE=no

# Download Linux kernel source automatically: yes|no
KERNEL_SRCS_INSTALL=no

# Grant the 'admin' role to the user specified by name
ADMIN_USER=administrator

# Configure SELinux automatically: yes|no
#CONFIGURE_SELINUX=yes
