# Ротация файлов ежедневно: 
daily
 
# Если размер увеличился до 256Мб, то ротируем не дожидаясь daily: 
maxsize 256M
 
# Выполняем ротацию 366 раз – далее удаляем старые: 
rotate 366
 
# Удалять ротированные файлы старше 366 дней (1 год): 
maxage 366
 
# create

# Использовать в названии старых файлов дату вместо простого номера: 
dateext
 
# Использовать формат даты ГОД-ММ-ДД: 
dateformate %Y-%m-%d.
 
# Сжимать файлы старых логов: 
compress
 
# Не сжимать самый новый лог файл: 
delaycompress
 
# Включить в конфигурацию правила ротации из директории /etc/logrotate.d: 
include /etc/logrotate.d
 
# Не ротировать если пустой лог: 
notifempty
 
# Не генерировать ошибку, если файла лога нет: 
missingok 
